### PR TITLE
Resolve tools/testein.py failure on OS X

### LINKED ISSUE #119: Invalid arguments to ps in testein.py on OS X
Running `tools/testein.py` fails on OS X, I think because it uses a different `ps` utility than that found in most linux distros. Here's the traceback I get:

```
Traceback (most recent call last):
  File "./tools/testein.py", line 501, in <module>
    main()
  File "./tools/testein.py", line 497, in main
    sys.exit(run_ein_test(**vars(args)))
  File "./tools/testein.py", line 428, in run_ein_test
    return 0
  File "./tools/testein.py", line 309, in __exit__
    self.stop()
  File "./tools/testein.py", line 352, in stop
    kill_subprocesses(self.proc.pid, lambda x: 'ipython' in x)
  File "./tools/testein.py", line 386, in kill_subprocesses
    '{2}'.format(command, proc.returncode, stderr))
RuntimeError: Command ['ps', '--ppid', '58047', '--format', 'pid,cmd', '--no-headers'] failed with code 1 and following error message:
ps: illegal option -- -
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
```

It appears I have the BSD version of `ps`; the man page is dated March 20, 2005.

I am not sure if it is possible to change the `ps` call to be compatible with both linux and mac -- I'll look into it. If not, the script could just do a system check and call the command differently on different systems.

P.S. Thank you for this wonderful, wonderful emacs plugin!

### PR DESCRIPTION
**Pull request by jhamrick**
This should fix #119. 

The arguments to `ps` do not translate nicely between versions, unfortunately, so it won't suffice to just have a single command. Instead, I changed it to try to run the GNU version first, and if that fails, then try the version that should work on OS X.

### CODE REVIEW

**Comment by tkf** [comment]
You don't need to use gnu options.  Linux ps should have unix options.  Let's keep the logic minimum, even if it requires a loop.  This way, it should run on Linux if it runs on Mac.  But It is sad that BSD ps does not have --ppid equivalent...

**Comment by jhamrick** [comment]
The issue I was trying to get around was that there is also no equivalent option for `--no-headers`. But actually, I realize that wouldn't matter if it's going to retrieve `ppid` and do the filtering in Python rather than with ps. I think then the correct command would be:

`ps -e -o ppid,pid,command`

And then check in the Python loop that `ppid` matches the target parent process.

**Comment by jhamrick** [comment]
Still failing with the `invalid literal for int() with base 10: ''` error. I think there are probably two spaces between the two pids, and so this is basically what's happening:

```
In [1]: "3423  2348  foo".split(' ', 2)
Out[1]: ['3423', '', '2348  foo']
```

Perhaps it should parse the `ppid` and `pid` out with a regex rather than using `split`? Something like this:

`re.findall(r"^([0-9]+)[ ]+([0-9]+)[ ]+(.*)$", line)`

**Comment by tkf** [comment]
Let's use None:

```
In [1]: "3423  2348  foo".split(None, 2)
Out[1]: ['3423', '2348', 'foo']

In [2]: str.split?
Type:       method_descriptor
Base Class: <type 'method_descriptor'>
String Form:<method 'split' of 'str' objects>
Namespace:  Python builtin
Docstring:
S.split([sep [,maxsplit]]) -> list of strings

Return a list of the words in the string S, using sep as the
delimiter string.  If maxsplit is given, at most maxsplit
splits are done. If sep is not specified or is None, any
whitespace string is a separator and empty strings are removed
from the result.
```

**Comment by jhamrick** [comment]
Oh, good idea, I had forgotten `split` could take `None`!

**Comment by tkf** [comment]
BTW, if you have extra power please squash commits into one commit :)

**Comment by tkf** [comment]
Merged.  Thank you!

BTW, github does not notify when someone push to an existing pull request so please put some comment next time :)

**Comment by jhamrick** [comment]
Ah, sorry, I didn't realize it didn't send a notification. Thanks for letting me know, I'll be sure to comment next time!

**Pull request merged**
